import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {LOCATIONS} from '../src/systems.js';
import {CITY_JOBS} from '../src/city-jobs.js';
const browser=await chromium.launch({headless:true}),errors=[],base=process.env.MAYA_URL||'http://localhost:5173';
async function open(age,mobile=false){const p=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1280,height:850},hasTouch:mobile,isMobile:mobile});p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>localStorage.setItem('maya-preferences','{"quality":"low"}'));await p.goto(base+'/?test');await p.waitForFunction(()=>window.__MAYA_TEST__);await p.click('#start-button');assert.equal((await p.evaluate(()=>window.__MAYA__.snapshot())).started,false);await p.fill('#player-name','Maya');await p.fill('#player-age',String(age));await p.screenshot({path:`/tmp/maya-onboarding-${age}.png`});await p.click('#start-button');assert.equal((await p.evaluate(()=>window.__MAYA__.snapshot())).started,true);return p;}
let page;
const snap=()=>page.evaluate(()=>window.__MAYA__.snapshot()),systems=()=>page.evaluate(()=>window.__MAYA_TEST__.nextSystems()),advance=s=>page.evaluate(s=>window.__MAYA_TEST__.advance(s),s),teleport=(x,z)=>page.evaluate(([x,z])=>window.__MAYA_TEST__.teleport(x,z),[x,z]),indoor=(x,z)=>page.evaluate(([x,z])=>window.__MAYA_TEST__.positionIndoor(x,z),[x,z]);
async function code(value){await page.keyboard.press('Backquote');await page.fill('#cheat-code',value);await page.click('#apply-cheat');}
async function hold(keys,seconds){await page.evaluate(([keys,seconds])=>{for(const key of keys)window.dispatchEvent(new KeyboardEvent('keydown',{key}));window.__MAYA_TEST__.advance(seconds);for(const key of keys)window.dispatchEvent(new KeyboardEvent('keyup',{key}));},[keys,seconds]);}
async function job(id){await page.keyboard.press('o');await page.click(`[data-city-job="${id}"]`);}
try{
 page=await open(17,true);await teleport(81,-65.4);await page.keyboard.press('e');assert.equal((await snap()).interior,null);await page.evaluate(()=>window.__MAYA_TEST__.enter('club'));assert.equal((await snap()).interior,null);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.reload();await page.waitForFunction(()=>window.__MAYA_TEST__);assert.deepEqual((await snap()).profile,{name:'Maya',age:17});await page.click('#start-button');assert.equal((await snap()).started,true);await page.close();console.log('PASS required name/age onboarding, persistence, mobile layout and club access denied below 18');
 page=await open(24);await page.evaluate(()=>window.__MAYA_TEST__.wallet(50000));await page.click('#settings-button');await page.selectOption('#time-select','23');await page.click('#resume-button');await page.evaluate(()=>window.__MAYA_TEST__.enter('club'));assert.equal((await snap()).interior,'club');await indoor(7,5);await page.keyboard.press('e');await page.click('[data-drink="beer"]');assert.ok((await snap()).intoxication>40);await page.keyboard.press('e');await page.click('#lounge-dance');await advance(.2);assert.equal((await systems()).loungeSeated,true);await page.screenshot({path:'/tmp/maya-lounge-011.png'});await advance(12.5);assert.equal((await systems()).loungeSeated,false);const before=await snap();await hold(['w'],.4);assert.ok(Math.hypot((await snap()).x-before.x,(await snap()).z-before.z)>.5,'can walk away after seated dance');
 await page.evaluate(()=>window.__MAYA_TEST__.enter('home'));await page.waitForTimeout(1300);assert.equal((await systems()).windows,true);await page.evaluate(()=>window.__MAYA_TEST__.view('shoulder',0));await indoor(0,-5);await page.screenshot({path:'/tmp/maya-window-011.png'});console.log('PASS adult lounge purchase, drink effect, seated performance exit and rendered exterior windows');
 await teleport(0,-280);await page.keyboard.press('m');await page.fill('#map-search','Hospital');assert.ok(await page.locator('[data-place]').count());await page.locator('[data-place]').first().click();await page.click('#map-plus');await page.locator('[data-map-filter="vehicles"]').uncheck();await page.screenshot({path:'/tmp/maya-map-011.png'});await page.click('#map-close');await advance(4.2);assert.ok((await systems()).mapRoute>0);console.log('PASS searchable map, zoom, layer filtering and generated route');
 const gunshop=LOCATIONS.find(l=>l.id==='weapons');await teleport(gunshop.x,gunshop.z);await page.keyboard.press('e');await page.click('#buy-bazooka');assert.equal((await snap()).inventory.bazooka,true);assert.equal((await snap()).inventory.missile,3);await page.click('#shop-close');await teleport(0,-300);await page.keyboard.press('4');await page.evaluate(()=>window.__MAYA_TEST__.aimAt(0,-270));assert.equal((await snap()).inventory.missile,2);await page.evaluate(()=>window.__MAYA_TEST__.aimAt(0,-270));assert.equal((await snap()).inventory.missile,2);await advance(4);await code('PEACE');await page.keyboard.press('1');await teleport(0,-300);
 await page.evaluate(()=>window.__MAYA_TEST__.residentAt('resident-0',1.8,-300));let health=(await snap()).health;await page.evaluate(()=>window.__MAYA_TEST__.aimAt(1.8,-300));await advance(.1);assert.equal((await page.evaluate(()=>window.__MAYA_TEST__.people())).find(p=>p.id==='resident-0').action,'punch');await advance(.5);assert.ok((await snap()).health<health,'civilian retaliates after windup');const cash=(await snap()).cashDrops.find(d=>d.source==='resident-0');assert.ok(cash);await teleport(cash.x,cash.z);const money=(await snap()).money;await page.keyboard.press('e');assert.equal((await snap()).money,money+cash.value);await page.evaluate(()=>window.__MAYA_TEST__.injure('resident-0',100));await advance(.5);assert.equal((await page.evaluate(()=>window.__MAYA_TEST__.people())).find(p=>p.id==='resident-0').action,'death');assert.equal((await snap()).cashDrops.filter(d=>d.source==='resident-0').length,0);console.log('PASS gun-shop launcher, finite rockets, punch retaliation, death animation and one-time cash');
 await code('PEACE');const officer=(await snap()).footPolice[2];await teleport(officer.x+4,officer.z);health=(await snap()).health;await page.evaluate(id=>window.__MAYA_TEST__.hurtOfficer(id,10),officer.id);await advance(2);assert.ok((await snap()).health<health,'armed walking officer fires back');await code('ARMOR');await code('PEACE');
 // Repeat three real favors to unlock recruitment rather than setting the trust counter.
 for(let i=0;i<3;i++){await teleport(0,-280);await page.evaluate(()=>window.__MAYA_TEST__.residentAt('resident-10',1,-280));await page.keyboard.press('e');await page.click('#ask-favor');await page.click('#accept-favor');const errand=(await snap()).errand;const target=LOCATIONS.find(l=>l.id===errand.target);await teleport(target.x,target.z);await page.keyboard.press('e');assert.equal((await snap()).errand,null);}
 await teleport(0,-280);await page.evaluate(()=>window.__MAYA_TEST__.residentAt('resident-10',1,-280));await page.keyboard.press('e');await page.click('#recruit-person');assert.ok((await snap()).crew.includes('resident-10'));await advance(.2);await hold(['w'],.7);await advance(2);assert.ok((await page.evaluate(()=>window.__MAYA_TEST__.people())).find(p=>p.id==='resident-10').following);console.log('PASS walking police retaliation, three favor deliveries and earned companion recruitment');
 const car=(await page.evaluate(()=>window.__MAYA_TEST__.cars())).find(c=>c.kind==='parked'&&c.health>90&&!c.spec.twoWheel);await teleport(0,-280);await page.evaluate(id=>window.__MAYA_TEST__.setCar(id,{x:0,z:-280,speed:0,angle:0,impulseX:0,impulseZ:0,health:100}),car.id);await teleport(2.5,-280);await page.keyboard.press('f');await advance(2);assert.equal((await snap()).driving,true);await advance(.2);assert.equal((await page.evaluate(()=>window.__MAYA_TEST__.people())).find(p=>p.id==='resident-10').vehicle,car.id);await page.keyboard.press('f');await advance(2);assert.equal((await snap()).driving,false);
 const ambulance=(await page.evaluate(()=>window.__MAYA_TEST__.cars())).find(c=>c.kind==='ambulance'&&c.health>50);await teleport(0,-290);await page.evaluate(id=>window.__MAYA_TEST__.setCar(id,{x:0,z:-290,speed:0,angle:0,path:[],health:100,impulseX:0,impulseZ:0}),ambulance.id);await teleport(2.5,-290);await page.keyboard.press('f');await advance(2);assert.equal((await snap()).driving,true);assert.equal((await page.evaluate(()=>window.__MAYA_TEST__.cars())).find(c=>c.id===ambulance.id).officialType,'ambulance');await job('rescue');
 for(let i=0;i<3;i++){const t=(await snap()).job.target;assert.equal(await page.evaluate(t=>window.__MAYA_TEST__.blocked(t.x,t.z),t),false,'job stop reachable');await page.evaluate(([id,t])=>window.__MAYA_TEST__.setCar(id,{x:t.x,z:t.z,speed:0,impulseX:0,impulseZ:0}),[ambulance.id,t]);await advance(.04);await page.keyboard.press('e');if(i<2)assert.equal((await snap()).job.stage,i+1);}
 assert.equal((await snap()).job,null);assert.equal((await snap()).jobRecords.rescue,1);await page.keyboard.press('p');await page.reload();await page.waitForFunction(()=>window.__MAYA_TEST__);await page.click('#start-button');assert.equal((await snap()).jobRecords.rescue,1);assert.ok((await snap()).crew.includes('resident-10'));await advance(.1);assert.ok((await page.evaluate(()=>window.__MAYA_TEST__.people())).find(p=>p.id==='resident-10').following,'saved companion rejoins after loading');console.log('PASS companion ride-along, drivable official ambulance, complete rescue route and persistence');
 await teleport(-250,40);await code('ARMOR');await job('escort');await page.keyboard.press('e');assert.equal((await snap()).job.stage,1);await teleport(-250,51);await advance(4);const a=await systems();assert.ok(a.jobActor.z>44,'escort walks toward player');await teleport(-250,56);await advance(3);await page.keyboard.press('e');assert.equal((await snap()).job.stage,2);await teleport(-246,66);await advance(4);await page.keyboard.press('e');assert.equal((await snap()).job,null);assert.equal((await snap()).jobRecords.escort,1);
 const dog=(await systems()).animals.find(a=>a.type==='dog');await teleport(dog.x,dog.z);await page.keyboard.press('e');assert.equal((await systems()).animals.find(a=>a.id===dog.id).friend,true);assert.equal((await systems()).birds,12);await teleport(0,-280);await code('HOPUP');await hold([' '],.2);assert.ok((await systems()).jump>1);await advance(2);await code('TEMPEST');await advance(.1);assert.equal((await snap()).tornado.warning,true);await advance(5.5);assert.equal((await snap()).tornado.warning,false);await page.screenshot({path:'/tmp/maya-tornado-011.png'});await page.evaluate(()=>window.__MAYA_TEST__.enter('home'));health=(await snap()).health;await advance(2);assert.equal((await snap()).health,health);console.log('PASS moving escort mission, friendly dog, birds, high jump and tornado shelter');
 assert.deepEqual(errors,[]);console.log('PASS no runtime errors');
}finally{await browser.close();}
