import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {seedProfile} from './profile-fixture.mjs';
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1280,height:850}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));await seedProfile(page);await page.addInitScript(()=>localStorage.setItem('maya-preferences','{"quality":"low"}'));
const snap=()=>page.evaluate(()=>window.__MAYA__.snapshot()),deep=()=>page.evaluate(()=>window.__MAYA_TEST__.lifeDepth()),advance=n=>page.evaluate(n=>window.__MAYA_TEST__.advance(n),n),teleport=(x,z)=>page.evaluate(([x,z])=>window.__MAYA_TEST__.teleport(x,z),[x,z]);
async function openPhone(){await page.click('#phone-button');assert.equal(await page.evaluate(()=>document.activeElement.id),'phone-back');await page.keyboard.press('Shift+Tab');assert.ok(await page.evaluate(()=>document.activeElement.getClientRects().length>0));}
try{
 await page.goto((process.env.MAYA_URL||'http://localhost:5180')+'/?test');await page.waitForFunction(()=>window.__MAYA_TEST__);await page.click('#start-button');await page.evaluate(()=>window.__MAYA_TEST__.wallet(20000));
 await teleport(33,-17.4);await page.keyboard.press('e');assert.equal((await snap()).presentation.active,true);await page.locator('[data-outfit="harbor"]').hover();await page.waitForTimeout(300);assert.equal((await snap()).presentation.preview,'outfit:harbor');const money=(await snap()).money;await page.click('[data-outfit="harbor"]');assert.equal((await snap()).money,money-240);assert.equal((await deep()).playerColor,'467582');await page.click('[data-outfit="harbor"]');assert.equal((await snap()).money,money-240);await page.screenshot({path:'/tmp/maya-tailor-012.png'});await page.click('#close-modal');
 await page.evaluate(()=>window.__MAYA_TEST__.enter('tailor'));const items=await page.evaluate(()=>window.__MAYA_TEST__.newSystems().items);assert.equal(items.filter(i=>i.id.startsWith('outfit-')).length,6);await page.evaluate(()=>window.__MAYA_TEST__.positionIndoor(0,6));await page.keyboard.press('e');assert.equal((await snap()).presentation.active,true);await page.click('#close-modal');await teleport(0,-280);
 await page.evaluate(()=>window.__MAYA_TEST__.residentAt('resident-10',1,-280));await page.keyboard.press('e');const a=(await snap()).presentation;await page.waitForTimeout(300);assert.ok((await snap()).presentation.time>a.time);await page.click('#exchange-number');assert.ok((await snap()).phone.contacts.includes('resident-10'));await page.click('#say-goodbye');console.log('PASS physical clothing store, animated previews, single-charge outfits and exchanging numbers');
 for(let i=0;i<4;i++){await page.evaluate(()=>window.__MAYA_TEST__.residentAt('resident-10',1,-280));await page.keyboard.press('e');await page.click('#say-goodbye');}await teleport(0,-270);await openPhone();await page.click('[data-app="contacts"]');await page.click('[data-call="resident-10"]');await page.waitForFunction(()=>window.__MAYA__.snapshot().phone.call.phase==='connected');assert.match(await page.locator('#call-status').innerText(),/on my way/);await page.click('#phone-put-away');await advance(3);const friend=(await page.evaluate(()=>window.__MAYA_TEST__.people())).find(p=>p.id==='resident-10');assert.ok(friend.z>-278,'called friend walks to shared location');console.log('PASS friend contact calls produce a physical meetup');
 const car=(await page.evaluate(()=>window.__MAYA_TEST__.cars())).find(c=>c.kind==='parked'&&!c.spec.twoWheel&&c.health>80);await page.evaluate(id=>window.__MAYA_TEST__.setCar(id,{x:0,z:-280,speed:0,angle:0,impulseX:0,impulseZ:0}),car.id);await teleport(2.5,-280);await page.keyboard.press('f');await advance(2);assert.equal((await snap()).driving,true);assert.equal((await deep()).driverColor,'467582');await page.keyboard.press('n');assert.equal((await snap()).radio,'lotus');assert.equal((await deep()).radio.station,'lotus');await page.keyboard.press('f');await advance(2);
 const truck=(await page.evaluate(()=>window.__MAYA_TEST__.cars())).find(c=>c.model==='truck');assert.ok(truck);await teleport(truck.x+5,truck.z);assert.equal((await deep()).radio.source,truck.id);console.log('PASS clothing visible while driving, radio switching and a physical music truck');
 await openPhone();await page.click('[data-app="games"]');await page.click('[data-game="snake"]');await page.waitForFunction(()=>window.__MAYA_TEST__.lifeDepth().snake.over);await page.screenshot({path:'/tmp/maya-snake-012.png'});await page.click('#phone-back');await page.click('[data-game="memory"]');const cards=(await deep()).memory.cards;for(let i=0;i<6;i++){const ids=cards.map((v,n)=>v===i?n:-1).filter(n=>n>=0);await page.click(`[data-memory="${ids[0]}"]`);if(i===5){await page.evaluate(i=>{document.querySelector('[data-memory="'+i+'"]').click();document.getElementById('phone-put-away').click();},ids[1]);assert.equal((await snap()).phone.memoryBest,6);await openPhone();await page.click('[data-app="games"]');await page.click('[data-game="memory"]');}else await page.click(`[data-memory="${ids[1]}"]`);}await page.waitForFunction(()=>window.__MAYA__.snapshot().phone.memoryBest===6);await page.click('#phone-back');await page.click('#phone-back');await page.click('[data-app="messages"]');await page.click('[data-offer="escort"]');assert.equal((await snap()).job.id,'escort');assert.ok((await snap()).phone.read.includes('escort'));await page.keyboard.press('o');await page.click('#cancel-city-job');await page.click('#close-modal');console.log('PASS playable phone games, persistent score and accepting a job from messages');
 // Call from a clear road close to the station; the request must move a unit, not change wanted level.
 await teleport(-93,-30);await openPhone();await page.click('[data-app="contacts"]');await page.click('[data-call="police"]');await page.waitForFunction(()=>window.__MAYA__.snapshot().phone.call.phase==='connected');assert.match(await page.locator('#call-status').innerText(),/coming/);assert.equal((await snap()).heat,0);await page.click('#phone-put-away');await advance(7);let calls=await page.evaluate(()=>window.__MAYA_TEST__.serviceCalls());assert.ok(calls.some(c=>c.kind==='police'));await advance(18);
 await teleport(-165,0);await openPhone();await page.evaluate(()=>window.__MAYA_TEST__.serviceReady('ambulance',-174,-6));await page.click('[data-app="contacts"]');await page.click('[data-call="ambulance"]');await page.waitForFunction(()=>window.__MAYA__.snapshot().phone.call.phase==='connected');assert.match(await page.locator('#call-status').innerText(),/coming/);await page.click('#phone-put-away');await advance(12);calls=await page.evaluate(()=>window.__MAYA_TEST__.serviceCalls());assert.ok(calls.some(c=>c.kind==='ambulance'));console.log('PASS ringing/connected service calls and physical police/ambulance dispatch without wanted heat');
 await page.keyboard.press('p');await page.reload();await page.waitForFunction(()=>window.__MAYA_TEST__);await page.click('#start-button');assert.equal((await snap()).wardrobe.equipped,'harbor');assert.equal((await snap()).radio,'lotus');assert.ok((await snap()).phone.contacts.includes('resident-10'));assert.equal((await snap()).phone.memoryBest,6);
 const mobile=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});mobile.on('pageerror',e=>errors.push(e.message));await seedProfile(mobile);await mobile.goto((process.env.MAYA_URL||'http://localhost:5180')+'/?test');await mobile.waitForFunction(()=>window.__MAYA_TEST__);await mobile.click('#start-button');await mobile.click('#phone-button');await mobile.click('[data-app="games"]');await mobile.click('[data-game="memory"]');assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await mobile.screenshot({path:'/tmp/maya-phone-mobile-012.png'});await mobile.close();assert.deepEqual(errors,[]);console.log('PASS saved wardrobe/contacts/radio/game records and mobile phone layout with no runtime errors');
}finally{await browser.close();}
