import {seedProfile} from './profile-fixture.mjs';
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1280,height:850}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>localStorage.setItem('maya-preferences',JSON.stringify({quality:'low',sensitivity:1})));
const snap=()=>page.evaluate(()=>window.__MAYA__.snapshot());
const advance=s=>page.evaluate(s=>window.__MAYA_TEST__.advance(s),s);
const teleport=(x,z)=>page.evaluate(([x,z])=>window.__MAYA_TEST__.teleport(x,z),[x,z]);
const indoor=(x,z)=>page.evaluate(([x,z])=>window.__MAYA_TEST__.positionIndoor(x,z),[x,z]);
async function hold(keys,seconds){await page.evaluate(([keys,seconds])=>{for(const key of keys)window.dispatchEvent(new KeyboardEvent('keydown',{key}));window.__MAYA_TEST__.advance(seconds);for(const key of keys)window.dispatchEvent(new KeyboardEvent('keyup',{key}));},[keys,seconds]);}
async function code(value){await page.keyboard.press('Backquote');await page.fill('#cheat-code',value);await page.click('#apply-cheat');}
try{
 await seedProfile(page);await page.goto((process.env.MAYA_URL||'http://localhost:5173')+'/?test');await page.waitForFunction(()=>window.__MAYA_TEST__);await page.screenshot({path:'/tmp/maya-welcome-010.png'});await page.click('#start-button');await page.evaluate(()=>window.__MAYA__.assetsReady);
 assert.equal(await page.locator('link[rel=icon][type="image/svg+xml"]').getAttribute('href'),'/assets/maya-emblem.svg');assert.equal(await page.locator('meta[property="og:image"]').getAttribute('content'),'/assets/maya-social.png');assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--burgundy').trim()),'#a62646');
 const cars=await page.evaluate(()=>window.__MAYA_TEST__.cars());for(const model of ['bicycle','motorcycle','bus','van'])assert.ok(cars.some(c=>c.model===model));assert.equal((await snap()).familyCount,4);
 await page.evaluate(()=>window.__MAYA_TEST__.wallet(50000));await teleport(7,-282);await page.keyboard.press('e');for(const gear of ['jetpack','parachute','grenade','c4','missile'])await page.click(`[data-gear="${gear}"]`);await page.click('[data-air="helicopter"]');await page.keyboard.press('e');await page.click('[data-air="plane"]');assert.deepEqual((await snap()).ownedAir,['helicopter','plane']);
 console.log('PASS emblem branding, vehicle variety and real equipment/aircraft purchases');
 for(const model of ['bicycle','motorcycle','bus']){const c=cars.find(c=>c.model===model);await teleport(c.x+2.5,c.z);await page.keyboard.press('f');await advance(2);assert.equal((await snap()).driving,true,model+' can be mounted');const start=await snap();await hold(['w'],1);const moved=await snap();assert.ok(Math.hypot(moved.x-start.x,moved.z-start.z)>1,model+' moves under player control');if(model==='bicycle'){await page.evaluate(()=>window.__MAYA_TEST__.view('shoulder',Math.PI));await page.screenshot({path:'/tmp/maya-bicycle-010.png'});}await hold([' '],1.5);await page.keyboard.press('f');await advance(2);assert.equal((await snap()).driving,false,model+' can be exited');}
 console.log('PASS bicycle, motorcycle and bus mounting, driving, braking and exit');
 await teleport(0,-280);await page.evaluate(()=>window.__MAYA_TEST__.view('top',0));await page.keyboard.press('x');await hold([' '],2);let s=await snap();assert.ok(s.altitude>20&&s.fuel<100);assert.equal(s.flightMode,'jetpack');await page.waitForTimeout(1200);s=await snap();assert.ok(s.cameraY>s.altitude&&s.cameraY<s.altitude+90,'camera height must not accumulate altitude every frame');await page.keyboard.press('l');assert.equal((await snap()).inventory.missile,0);await advance(3.5);assert.equal((await snap()).ordnance.length,0);await page.keyboard.press('k');assert.equal((await snap()).flightMode,'parachute');await advance(9);assert.equal((await snap()).flightMode,null);assert.equal((await snap()).altitude,0);
 await code('PEACE');await teleport(4,-264);await page.keyboard.press('f');assert.equal((await snap()).flightMode,'helicopter');await hold([' '],2);await page.keyboard.press('f');assert.equal((await snap()).flightMode,'helicopter','aircraft cannot be exited in midair');await page.keyboard.press('v');await page.waitForTimeout(800);await page.screenshot({path:'/tmp/maya-flight-010.png'});await hold(['Control'],3);await page.keyboard.press('f');assert.equal((await snap()).flightMode,null);
 await teleport(4,-306);await page.keyboard.press('f');assert.equal((await snap()).flightMode,'plane');await hold([' '],.5);assert.equal((await snap()).altitude,0);await hold(['w',' '],3);assert.ok((await snap()).altitude>10);await page.keyboard.press('k');await advance(10);assert.equal((await snap()).flightMode,null);
 console.log('PASS jetpack, stable altitude camera, missile, parachute, helicopter and speed-dependent plane takeoff');
 await teleport(0,-300);await code('PEACE');await code('ARMORY');await advance(2);await page.keyboard.press('t');assert.ok((await snap()).ordnance.some(p=>p.kind==='c4'));await teleport(0,-290);await page.keyboard.press('y');assert.equal((await snap()).ordnance.filter(p=>p.kind==='c4').length,0);await advance(.8);const count=(await snap()).inventory.grenade;await page.keyboard.press('g');assert.equal((await snap()).inventory.grenade,count-1);await advance(3);assert.equal((await snap()).ordnance.length,0);
 await code('PEACE');await page.evaluate(()=>window.__MAYA_TEST__.enter('home'));await indoor(9.8,5.5);await page.keyboard.press('e');assert.equal((await snap()).buildingJobs.home,1);await indoor(9.8,8.5);await page.keyboard.press('e');assert.equal((await snap()).floor,1);
 await indoor(-6,-2);await page.keyboard.press('e');await advance(4.1);assert.equal((await snap()).buildingJobs.home,2);const money=(await snap()).money;await indoor(6,-2);await page.keyboard.press('e');await advance(4.1);assert.equal((await snap()).buildingJobs.home,3);assert.equal((await snap()).money,money+220);await page.keyboard.press('e');await advance(4.1);assert.equal((await snap()).money,money+220);await page.screenshot({path:'/tmp/maya-upper-010.png'});
 console.log('PASS C4 placement and remote detonation, grenade fuse, furnished floors and one-time two-step work reward');
 await teleport(81,-65.4);await page.click('#settings-button');await page.selectOption('#time-select','23');await page.click('#resume-button');await page.keyboard.press('e');assert.equal((await snap()).interior,'club');await advance(.1);let systems=await page.evaluate(()=>window.__MAYA_TEST__.newSystems());assert.equal(systems.clubDancers.length,4);assert.ok(systems.clubDancers.every(d=>d.age>=25&&d.visible));await indoor(-3,-3);await page.keyboard.press('e');assert.match(await page.locator('#modal-body').innerText(),/Nadeesha/);await page.click('#say-goodbye');await page.evaluate(()=>window.__MAYA_TEST__.view('top',0));await page.screenshot({path:'/tmp/maya-club-010.png'});
 await page.click('#settings-button');await page.selectOption('#time-select','13');await page.click('#resume-button');await advance(.1);systems=await page.evaluate(()=>window.__MAYA_TEST__.newSystems());assert.ok(systems.clubDancers.every(d=>!d.visible));await teleport(-252,40);await advance(.1);systems=await page.evaluate(()=>window.__MAYA_TEST__.newSystems());assert.ok(systems.families.every(p=>p.routine==='school'));assert.ok(systems.families.some(p=>p.age<18&&p.outfit==='work'));assert.ok(systems.families.every(p=>p.visible));
 await page.keyboard.press('p');await page.reload();await page.waitForFunction(()=>window.__MAYA_TEST__);assert.equal((await snap()).buildingJobs.home,3);assert.equal((await snap()).inventory.jetpack,true);assert.deepEqual((await snap()).ownedAir,['helicopter','plane']);
 console.log('PASS adult club schedules and dialogue, family schedules, persistent jobs and equipment');
 const mobile=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});mobile.on('pageerror',e=>errors.push(e.message));
 await mobile.addInitScript(()=>{localStorage.setItem('maya-preferences','{"quality":"low"}');localStorage.setItem('maya-city-v1',JSON.stringify({version:2,x:0,z:-280,hour:13,money:2500,equipment:{jetpack:true,parachute:true,missile:2}}));});
 await seedProfile(mobile);await mobile.goto((process.env.MAYA_URL||'http://localhost:5173')+'/?test');await mobile.waitForFunction(()=>window.__MAYA_TEST__);await mobile.click('#start-button');await mobile.click('#equipment-button');await mobile.click('#equip-pack');await mobile.waitForSelector('#flight-controls:visible');
 const client=await mobile.context().newCDPSession(mobile),box=await mobile.locator('#flight-controls [data-key=" "]').boundingBox();await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:box.x+box.width/2,y:box.y+box.height/2}]});await mobile.evaluate(()=>window.__MAYA_TEST__.advance(2));await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(await mobile.evaluate(()=>window.__MAYA__.snapshot().altitude>20));const origin=await mobile.evaluate(()=>window.__MAYA__.snapshot());await mobile.evaluate(()=>{window.dispatchEvent(new KeyboardEvent('keydown',{key:'d'}));window.__MAYA_TEST__.advance(.25);window.dispatchEvent(new KeyboardEvent('keyup',{key:'d'}));});const shifted=await mobile.evaluate(()=>window.__MAYA__.snapshot());assert.ok((shifted.x-origin.x)*Math.cos(origin.cameraAngle)-(shifted.z-origin.z)*Math.sin(origin.cameraAngle)>1,'air movement follows screen-right');
 assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await mobile.screenshot({path:'/tmp/maya-mobile-flight-010.png'});await mobile.close();
 console.log('PASS compact mobile equipment menu, ascent control and layout');assert.deepEqual(errors,[]);
}finally{await browser.close();}
