import {distance} from './physics.js';
import {createPerson,animatePerson} from './actor-models.js';
export const CITY_JOBS={
 taxi:{name:'The last three fares',contact:'Nimali · night dispatcher',brief:'Pick up passengers around the city. Stop at each curb, keep the ride smooth and finish the route before the shift ends.',seconds:240,reward:1000,vehicle:'passenger',stops:[{x:-10,z:24,name:'Pick up Dilani',pickup:true},{x:-163,z:-8,name:'Drop Dilani at the hospital'},{x:-237,z:43,name:'Pick up Isuru',pickup:true},{x:61,z:54,name:'Drop Isuru at the workshop'},{x:-10,z:24,name:'Pick up Meena',pickup:true},{x:-61,z:-58,name:'Drop Meena at the temple'}]},
 rescue:{name:'The golden hour',contact:'Sahani · Maya General',brief:'Bring an ambulance to collect a medical team, reach the injured patient, then return to the hospital. Rough driving costs patient condition.',seconds:190,reward:1400,vehicle:'ambulance',stops:[{x:-163,z:-8,name:'Collect the medical team',pickup:true},{x:-237,z:43,name:'Collect the injured patient',pickup:true},{x:-163,z:-8,name:'Deliver patient to Maya General'}]},
 courier:{name:'Before the shutters close',contact:'Arun · workshop owner',brief:'Collect refrigeration parts, deliver them to the farm, then take the repaired crate to the harbor. Keep the cargo intact.',seconds:200,reward:1250,vehicle:'any',stops:[{x:61,z:54,name:'Collect the sealed parts'},{x:-211,z:180.6,name:'Deliver parts at the farm'},{x:29,z:184.6,name:'Deliver the repaired crate at the harbor'}]},
 escort:{name:'A safe walk home',contact:'Saroja · neighborhood volunteer',brief:'Meet the adult librarian, walk together through the park and see her home. She waits when you get too far ahead. Bring a trusted friend for company.',seconds:150,reward:650,vehicle:'foot',stops:[{x:-250,z:40,name:'Meet librarian Anjali',pickup:true},{x:-250,z:56,name:'Walk together through the park'},{x:-246,z:66,name:'See Anjali safely home'}]},
};
export function validJobVehicle(job,car){return job.vehicle==='foot'?!car:!!car&&car.health>0&&(job.vehicle!=='ambulance'||car.officialType==='ambulance'||car.kind==='ambulance')&&(job.vehicle!=='passenger'||!car.spec.twoWheel);}
export function finishCityJob(s,job){if(job.paid||job.stage<CITY_JOBS[job.id].stops.length)return 0;job.paid=true;const payout=Math.round(CITY_JOBS[job.id].reward*(.65+job.condition/100*.35)+Math.max(0,job.time)*2);s.money+=payout;s.reputation=Math.min(100,s.reputation+3);s.jobRecords[job.id]=(s.jobRecords[job.id]||0)+1;return payout;}
export class CityJobs{
 constructor(scene,navigator){this.scene=scene;this.navigator=navigator;this.active=null;this.actor=null;}
 start(id,s){if(!CITY_JOBS[id]||this.active)return false;this.active={id,stage:0,time:CITY_JOBS[id].seconds,condition:100,started:false,paid:false,health:s.health,carHealth:s.driving?.health||100};const mesh=createPerson('#bd8e68','#a62646',{gender:'woman',variant:1});this.actor={mesh,x:CITY_JOBS[id].stops[0].x,z:CITY_JOBS[id].stops[0].z,route:[],repath:0};this.scene.add(mesh);return true;}
 target(){if(!this.active)return null;return CITY_JOBS[this.active.id].stops[this.active.stage]||null;}
 stop(){if(this.actor){this.actor.mesh.parent?.remove(this.actor.mesh);this.actor.mesh.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});}this.active=null;this.actor=null;}
 interact(s){const j=this.active,target=this.target();if(!j||s.interior||distance(s,target)>4.5)return null;const spec=CITY_JOBS[j.id];if(!validJobVehicle(spec,s.driving))return spec.vehicle==='foot'?'Meet your passenger on foot.':spec.vehicle==='ambulance'?'Bring an ambulance to this stop.':'Bring a working road vehicle.';if(s.driving&&Math.abs(s.speed)>2)return 'Stop safely before the pickup.';if(j.id==='escort'&&j.stage>0&&distance(this.actor,target)>5)return 'Wait for Anjali to catch up.';
 j.stage++;j.started=true;j.health=s.health;j.carHealth=s.driving?.health||100;if(j.stage===spec.stops.length){const paid=finishCityJob(s,j);this.stop();return `JOB COMPLETE · Rs. ${paid}`;}return 'Checkpoint complete · '+this.target().name;
 }
 update(dt,s){const j=this.active;if(!j)return null;j.time-=dt;const damage=Math.max(0,j.health-s.health)+Math.max(0,j.carHealth-(s.driving?.health??j.carHealth));j.condition=Math.max(0,j.condition-damage*.7);j.health=s.health;j.carHealth=s.driving?.health??j.carHealth;if(j.time<=0||j.condition<=10||s.health<=0||s.driving?.health<=0){const reason=j.time<=0?'Time ran out.':j.condition<=10||s.driving?.health<=0?'The passenger or cargo took too much damage.':'You were incapacitated.';this.stop();return 'JOB FAILED · '+reason+' Retry from City Jobs.';}
 const a=this.actor,spec=CITY_JOBS[j.id];if(!a)return null;
 if(j.id==='escort'&&j.started){if(a.mesh.parent!==this.scene)this.scene.add(a.mesh);if(!s.interior&&distance(a,s)>2&&distance(a,s)<16){if(s.elapsed>a.repath){a.route=this.navigator.route(a,s,.6);a.repath=s.elapsed+.8;}const p=a.route[0];if(p){const d=distance(a,p);if(d<.5)a.route.shift();else this.navigator.collision.move(a,(p.x-a.x)/d*dt*3.6,(p.z-a.z)/d*dt*3.6,.6);a.mesh.rotation.y=Math.atan2(s.x-a.x,s.z-a.z);animatePerson(a.mesh,s.elapsed,3.6);}}a.mesh.position.set(a.x,.3,a.z);a.mesh.visible=!s.interior;
 }else if(j.started&&s.driving&&['taxi','rescue'].includes(j.id)&&!spec.stops[j.stage].pickup){if(a.mesh.parent!==s.driving.mesh)s.driving.mesh.add(a.mesh);a.mesh.scale.setScalar(.6);a.mesh.position.set(.5,.42,.1);a.mesh.rotation.z=0;a.mesh.rotation.y=0;animatePerson(a.mesh,s.elapsed,0,false,true);a.mesh.visible=true;
 }else{if(a.mesh.parent!==this.scene)this.scene.add(a.mesh);const t=this.target();a.x=t.x+1.5;a.z=t.z;a.mesh.scale.setScalar(1);a.mesh.position.set(a.x,.3,a.z);a.mesh.visible=!s.interior&&!!t.pickup;a.mesh.rotation.z=j.id==='rescue'&&j.stage===1?1.35:0;animatePerson(a.mesh,s.elapsed,0);}}
}
