import {createPerson,animatePerson,dressPerson} from './actor-models.js';
import {distance} from './systems.js';
const FAMILY=[['Tara Perera',9,'School student','I am drawing every tree on our walk to school. Mum says the park has more than I can count.','#a62646'],['Neth Senanayake',12,'School student','I want to fix the school radio. My teacher has promised to show me how the tuning dial works.','#919947'],['Amani Joseph',10,'School student','My favorite library book is about sea turtles. I am making a poster for our class.','#6b879a'],['Saroja Perera',34,'School crossing volunteer','I walk with the neighborhood children and help keep their school route safe.','#a48669']];
export class Families{
 constructor(scene,navigator){this.navigator=navigator;this.people=FAMILY.map(([name,age,job,story,color],i)=>{const mesh=createPerson('#bd8e68',color,{gender:i===3?'woman':i===1?'boy':'girl',height:i===3?1:.61+i*.035,variant:i});scene.add(mesh);return {id:`family-${i}`,name,age,job,story,dialogue:i===3?'The school day ends at three. We take the quiet lane home.':'We are going to the library after school!',mesh,x:-256+i,z:39,health:100,relationship:0,met:false,helped:true,routine:'',outfit:'casual',route:[],removed:false,inside:null,color};});this.mode='';}
 update(dt,state){const mode=state.hour<7||state.hour>=19?'home':state.hour<15?'school':'park';if(this.mode!==mode){this.mode=mode;for(const [i,p] of this.people.entries()){p.routine=mode;p.outfit=mode==='school'?'work':'casual';dressPerson(p.mesh,p.outfit,mode==='school'?'#faf7ee':p.color);const goal=mode==='school'?{x:-258+i,z:40}:mode==='park'?{x:-246+i*.8,z:57}:{x:-260+i,z:42};p.route=this.navigator.route(p,goal,.45);}}
 for(const [i,p] of this.people.entries()){p.mesh.visible=mode!=='home'&&!state.interior&&distance(p,state)<160;if(state.heat>0&&distance(p,state)<45){p.mesh.visible=false;continue;}const next=p.route[0];if(next){const d=distance(p,next);if(d<.4)p.route.shift();else{this.navigator.collision.move(p,(next.x-p.x)/d*dt*1.4,(next.z-p.z)/d*dt*1.4,.4);p.mesh.rotation.y=Math.atan2(next.x-p.x,next.z-p.z);}}animatePerson(p.mesh,state.elapsed+i,next?1.4:0);p.mesh.position.set(p.x,.3,p.z);}
 }
 nearest(s){return this.people.find(p=>p.mesh.visible&&distance(p,s)<3);}
}
