import {createPerson,animatePerson} from './actor-models.js';
import {weaponModel} from './combat.js';
import {stepWalker} from './navigation-recovery.js';
import {distance} from './physics.js';
import {react,reactionPose} from './reactions.js';
export class FootPatrols{
 constructor(scene,navigator,combat,report){this.scene=scene;this.navigator=navigator;this.combat=combat;this.report=report;this.people=[[-101,-14],[-153,8],[-247,39]].map(([x,z],i)=>{const mesh=createPerson('#bd8e68','#637d91',{variant:i}),gun=weaponModel('pistol');gun.position.set(.44,1.3,.25);mesh.add(gun);scene.add(mesh);return {id:'foot-officer-'+i,x,z,home:{x,z},mesh,gun,health:100,dead:false,police:true,name:['Officer Chaminda','Officer Malini','Officer Suresh'][i],age:30+i*4,job:'Foot patrol officer',story:'I patrol this neighborhood on foot and check on the shopkeepers each day.',dialogue:'Keep the streets safe. We respond to violence, even when no patrol car is nearby.',routine:'neighborhood patrol',outfit:'work',relationship:0,helped:true,route:[],nextRoute:0,shotAt:0,aggressiveUntil:0};});}
 targets(){return this.people.filter(p=>!p.dead).map(p=>({x:p.x,z:p.z,footOfficer:p}));}
 hurt(p,damage,s,crime=true){if(p.dead)return;p.health=Math.max(0,p.health-damage);if(crime)p.aggressiveUntil=s.elapsed+35;p.injured=p.health<=20;react(p.mesh,p.health<=0?'death':p.injured?'down':'hit',s.elapsed);if(!p.health){p.dead=true;this.combat.blood(this.scene,p,s.elapsed);this.onDeath?.(p,s);}if(crime)this.report(p,s);this.onInjury?.(p,s);}
 update(dt,s,onDamage){for(const [i,p] of this.people.entries()){p.hitCooldown=Math.max(0,(p.hitCooldown||0)-dt);if(p.impulse){this.navigator.collision.move(p,p.impulse.x*dt,p.impulse.z*dt,.6);p.impulse.x*=Math.exp(-dt*4);p.impulse.z*=Math.exp(-dt*4);p.mesh.position.x=p.x;p.mesh.position.z=p.z;}if(p.removed||p.medicalHold||p.injured&&!p.dead){p.mesh.visible=!p.removed&&!s.interior;reactionPose(p.mesh,s.elapsed);continue;}if(p.dead){reactionPose(p.mesh,s.elapsed);p.mesh.visible=s.elapsed-p.mesh.userData.action.now<60&&!s.interior;continue;}p.mesh.visible=!s.interior&&distance(p,s)<170;const hostile=p.aggressiveUntil>s.elapsed||s.heat>0&&distance(p,s)<30;const goal=hostile&&!s.interior?s:{x:p.home.x+Math.sin(s.elapsed*.035+i)*5,z:p.home.z+Math.cos(s.elapsed*.035+i)*7};
  const sees=this.navigator.collision.lineClear(p,s,.1,1.4),pace=stepWalker(p,goal,this.navigator,dt,s.elapsed,{speed:hostile?4:1.4,stop:hostile?7:1,visible:!hostile||sees});p.mesh.position.set(p.x,.3,p.z);if(p.facing!=null)p.mesh.rotation.y=p.facing;animatePerson(p.mesh,s.elapsed,pace,hostile);
  if(hostile&&!s.interior&&s.altitude<4&&distance(p,s)<30&&this.navigator.collision.lineClear(p,s,.1,1.4)){p.mesh.rotation.y=Math.atan2(s.x-p.x,s.z-p.z);if(!p.aim&&s.elapsed>p.shotAt)p.aim={x:s.x,z:s.z,at:s.elapsed+.55};if(p.aim&&s.elapsed>=p.aim.at){this.combat.tracer(p,p.aim,s.elapsed);react(p.mesh,'shoot',s.elapsed);this.combat.audio.play('gunshot');if(distance(p.aim,s)<(s.driving?2:.85)&&s.dodge<=0)onDamage(s.driving?7:14);p.aim=null;p.shotAt=s.elapsed+.8;}}else p.aim=null;reactionPose(p.mesh,s.elapsed);
 }}
}
