import {FACTIONS,TERRITORIES,territoryOwner} from './city-activities.js';
import {BOUNDS,LOCATIONS} from './systems.js';
export function mapProjection(canvas,state,big=false){const w=canvas.width,h=canvas.height,scale=big?Math.min(w/480,h/650)*(state.mapZoom||1):w/(state.driving?210:150),cx=big?(state.mapCenter?.x??-104):state.x,cz=big?(state.mapCenter?.z??-24):state.z;return {w,h,scale,cx,cz,px:x=>w/2+(x-cx)*scale,pz:z=>h/2+(z-cz)*scale};}
export function drawMap(canvas,state,world,cars,target,big=false){
 const ctx=canvas.getContext('2d'),{w,h,scale,px,pz}=mapProjection(canvas,state,big),filters=state.mapFilters||{services:true,people:true,vehicles:true};ctx.fillStyle='#383536';ctx.fillRect(0,0,w,h);
 if(state.roomMap&&!big){const sc=Math.min(w/25,h/23),x=v=>w/2+v*sc,z=v=>h/2+v*sc;ctx.fillStyle='#aaa186';ctx.fillRect(x(-11),z(-10),22*sc,20*sc);ctx.fillStyle='#383536';for(const s of state.roomMap.solids)ctx.fillRect(x(s.x-s.w/2),z(s.z-s.d/2),s.w*sc,s.d*sc);ctx.fillStyle='#faf7ee';ctx.font='18px Arial';for(const i of state.roomMap.items)ctx.fillText(i.id==='stairs'?'▲':'·',x(i.x)-5,z(i.z)+5);drawArrow(ctx,x(state.roomMap.x),z(state.roomMap.z),state.heading);ctx.fillStyle='#faf7ee';ctx.font='13px Arial';ctx.fillText(state.floor?'UPPER FLOOR':'GROUND FLOOR',12,20);return;}
 ctx.fillStyle='#777b4b';ctx.fillRect(px(BOUNDS.minX),pz(BOUNDS.minZ),(BOUNDS.maxX-BOUNDS.minX)*scale,(BOUNDS.maxZ-BOUNDS.minZ)*scale);ctx.fillStyle='#60643f';ctx.fillRect(px(-320),pz(-326),430*scale,220*scale);ctx.fillStyle='#919947';ctx.fillRect(px(-320),pz(145),210*scale,130*scale);
 for(const r of world.roadSegments){ctx.strokeStyle='#d8d2bd';ctx.lineWidth=r.width*scale;ctx.beginPath();ctx.moveTo(px(r.x1),pz(r.z1));ctx.lineTo(px(r.x2),pz(r.z2));ctx.stroke();}
 if(state.activities)for(const t of TERRITORIES){ctx.globalAlpha=.14;ctx.fillStyle=FACTIONS[territoryOwner(state.activities,t.id)].color;ctx.fillRect(px(t.x-t.w/2),pz(t.z-t.d/2),t.w*scale,t.d*scale);ctx.globalAlpha=1;}
 ctx.fillStyle='#bcb49c';ctx.strokeStyle='#383536';ctx.lineWidth=.7;for(const b of world.buildings){ctx.fillRect(px(b.x-b.w/2),pz(b.z-b.d/2),b.w*scale,b.d*scale);ctx.strokeRect(px(b.x-b.w/2),pz(b.z-b.d/2),b.w*scale,b.d*scale);}
 if(target){const route=state.mapRoute?.length?state.mapRoute:[state,target];ctx.strokeStyle='#a62646';ctx.lineWidth=big?4:5;ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(px(state.x),pz(state.z));for(const p of route)ctx.lineTo(px(p.x),pz(p.z));ctx.stroke();ctx.strokeStyle='#faf7ee';ctx.lineWidth=1;ctx.stroke();pin(target,'★','#a62646',big?10:9);}
 const labels=[];function pin(p,label,color,r=7){const x=px(p.x),y=pz(p.z);if(x<-20||x>w+20||y<-20||y>h+20)return;ctx.fillStyle=color;ctx.strokeStyle='#faf7ee';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#faf7ee';ctx.font=`bold ${r+2}px Arial`;ctx.textAlign='center';ctx.fillText(label,x,y+r*.4);ctx.textAlign='left';}
 if(filters.services)for(const l of LOCATIONS){const symbol={tailor:'S',weapons:'G',clinic:'+',home:'H',depot:'A',club:'C',garage:'V',tea:'T',race:'R',station:'P'}[l.id]||'◆';pin(l,symbol,l.id==='station'?'#46719a':l.id==='club'?'#a62646':'#565b2d');if(big){const x=px(l.x)+11,y=pz(l.z)-7;if(labels.every(p=>Math.abs(p.y-y)>13||Math.abs(p.x-x)>135)){ctx.font='11px Arial';const width=ctx.measureText(l.name).width;ctx.fillStyle='#383536df';ctx.fillRect(x-3,y-11,width+7,15);ctx.fillStyle='#faf7ee';ctx.fillText(l.name,x,y);labels.push({x,y});}}}
 if(filters.vehicles)for(const c of cars){if(c.kind==='removed')continue;ctx.fillStyle=c.kind==='police'?'#729dff':c.kind==='ambulance'?'#f09daf':'#383536';ctx.fillRect(px(c.x)-2,pz(c.z)-2,4,4);}
 if(filters.people){for(const p of state.mapPeople||[])pin(p,p.crew?'●':p.police?'P':p.animal?'!':'·',p.crew?'#397b77':p.police?'#46719a':'#a62646',big?7:6);}
 if(state.tornado){ctx.fillStyle='#a626463b';ctx.strokeStyle='#a62646';ctx.lineWidth=2;ctx.beginPath();ctx.arc(px(state.tornado.x),pz(state.tornado.z),30*scale,0,Math.PI*2);ctx.fill();ctx.stroke();pin(state.tornado,'!','#a62646',10);}
 drawArrow(ctx,px(state.x),pz(state.z),state.heading);ctx.fillStyle='#383536df';ctx.fillRect(w-36,8,28,33);ctx.fillStyle='#faf7ee';ctx.font='bold 13px Arial';ctx.fillText('N',w-27,23);ctx.fillText('↑',w-26,37);
 if(big){ctx.fillStyle='#383536e8';ctx.fillRect(12,h-37,170,25);ctx.strokeStyle='#faf7ee';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(20,h-22);ctx.lineTo(20+50*scale,h-22);ctx.stroke();ctx.fillStyle='#faf7ee';ctx.font='10px Arial';ctx.fillText('50 m · '+Math.round((state.mapZoom||1)*100)+'%',25+50*scale,h-18);}
}
function drawArrow(ctx,x,z,angle=0){ctx.save();ctx.translate(x,z);ctx.rotate(-angle+Math.PI);ctx.fillStyle='#a62646';ctx.strokeStyle='#faf7ee';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-10);ctx.lineTo(6,7);ctx.lineTo(0,3);ctx.lineTo(-6,7);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}
