import {SERVICE_CONTACTS,phoneNumber,PocketSnake,MemoryPairs} from './phone.js';
import {CITY_JOBS} from './city-jobs.js';
import {STATIONS} from './vehicle-radio.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class PhoneUI{
 constructor(phone,state,people,actions){Object.assign(this,{phone,state,people,actions});this.view='home';this.game=null;}
 open(view='home'){
  this.view=view;const p=this.phone,s=this.state,contacts=[...SERVICE_CONTACTS,...p.data.contacts.map(id=>this.people.find(p=>p.id===id)).filter(Boolean).map(p=>({id:p.id,name:p.name,number:phoneNumber(p.id)}))];
  let content='';
  if(view==='home')content=`<div class="phone-apps">${[['contacts','☎','Contacts',contacts.length+' numbers'],['messages','✉','Messages','4 job offers'],['radio','♫','Radio','Three original stations'],['games','▦','Games','Snake & Memory']].map(([id,icon,name,note])=>`<button data-app="${id}"><b>${icon}</b><strong>${name}</strong><small>${note}</small></button>`).join('')}</div><p class="phone-tip">Ask a neighbor to exchange numbers during a conversation.</p>`;
  if(view==='contacts')content=`<label class="phone-pin"><input id="call-pin" type="checkbox" ${s.waypoint?'':'disabled'}> Share map pin ${s.waypoint?'':'(pin a place first)'}</label><div class="phone-contacts">${contacts.map(c=>`<button data-call="${c.id}"><span><strong>${esc(c.name)}</strong><small>${c.number}</small></span><b>☎</b></button>`).join('')}</div><label class="phone-dial">Dial a number<input id="dial-number" inputmode="tel" maxlength="12"><button id="dial-call">CALL</button></label>`;
  if(view==='messages')content=Object.entries(CITY_JOBS).map(([id,j])=>`<article class="phone-message"><small>${esc(j.contact)}</small><h3>${esc(j.name)}</h3><p>${esc(j.brief)}</p><small>${j.seconds}s · Rs. ${j.reward} + bonus</small><button data-offer="${id}" ${s.jobActive?'disabled':''}>${s.jobActive?'Finish your current job':'ACCEPT JOB'}</button></article>`).join('');
  if(view==='radio')content=`<p>Choose the station in your vehicle. Passing sound trucks play Lotus Groove.</p>${STATIONS.map(r=>`<button class="radio-station ${s.radio===r.id?'selected':''}" data-station="${r.id}">${esc(r.name)} ${s.radio===r.id?'●':''}</button>`).join('')}`;
  if(view==='games')content=`<div class="phone-apps"><button data-game="snake"><b>↝</b><strong>Pocket Snake</strong><small>Best ${p.data.snakeBest}</small></button><button data-game="memory"><b>▦</b><strong>Memory Pairs</strong><small>${p.data.memoryBest?'Best '+p.data.memoryBest+' moves':'Find six pairs'}</small></button></div>`;
  if(view==='snake')content='<p id="phone-score">Use arrows or the direction pad.</p><canvas id="phone-game" width="288" height="288" aria-label="Snake game"></canvas><div class="phone-game-pad"><button data-turn="0,-1">↑</button><button data-turn="-1,0">←</button><button data-turn="0,1">↓</button><button data-turn="1,0">→</button></div><button id="restart-phone-game">RESTART</button>';
  if(view==='memory')content='<p id="phone-score">Find six matching pairs.</p><div class="memory-grid">'+Array.from({length:12},(_,i)=>`<button data-memory="${i}" aria-label="Card ${i+1}">?</button>`).join('')+'</div><button id="restart-phone-game">NEW GAME</button>';
  if(view==='call')content=`<div class="call-screen"><b class="call-pulse">☎</b><h3>${esc(contacts.find(c=>c.id===p.call?.id)?.name||'Call')}</h3><p id="call-status">${esc(p.call?.status||'Call ended')}</p><button id="hang-up">HANG UP</button></div>`;
  this.actions.show(`<div class="city-phone"><header><span>MAYA MOBILE</span><span>● 4G ▰</span></header><nav><button id="phone-back">‹</button><strong>${view.toUpperCase()}</strong><button id="phone-put-away">×</button></nav><div class="phone-screen">${content}</div><footer>MAYA MOBILE · KEEP IN TOUCH</footer></div>`,'phone');
  const q=id=>document.getElementById(id);q('phone-back').onclick=()=>this.open(['snake','memory'].includes(view)?'games':'home');q('phone-put-away').onclick=this.actions.close;
  document.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>this.open(b.dataset.app));document.querySelectorAll('[data-station]').forEach(b=>b.onclick=()=>{s.radio=b.dataset.station;this.actions.save();this.open('radio');});
  const dial=id=>{const point=q('call-pin')?.checked&&s.waypoint?s.waypoint:this.actions.position(),error=p.dial(id,point,s);if(error){this.actions.toast(error);return;}this.actions.audio.play('ui');this.open('call');};
  document.querySelectorAll('[data-call]').forEach(b=>b.onclick=()=>dial(b.dataset.call));if(q('dial-call'))q('dial-call').onclick=()=>{const c=contacts.find(c=>c.number===q('dial-number').value.replace(/\D/g,''));if(c)dial(c.id);else this.actions.toast('Number not in your contacts. Ask them to exchange numbers first.');};
  document.querySelectorAll('[data-offer]').forEach(b=>b.onclick=()=>{const id=b.dataset.offer;if(this.actions.job(id)){if(!p.data.read.includes(id))p.data.read.push(id);this.actions.save();this.actions.close();this.actions.toast('Job accepted · '+CITY_JOBS[id].name);}});
  document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>this.startGame(b.dataset.game));if(q('restart-phone-game'))q('restart-phone-game').onclick=()=>this.startGame(view);
  document.querySelectorAll('[data-turn]').forEach(b=>b.onclick=()=>this.game.turn(...b.dataset.turn.split(',').map(Number)));document.querySelectorAll('[data-memory]').forEach(b=>b.onclick=()=>{if(this.game.flip(Number(b.dataset.memory))){this.actions.audio.play('ui');this.update(0);}});
  if(q('hang-up'))q('hang-up').onclick=()=>{p.hangup();this.open('contacts');};
 }
 startGame(kind){this.game=kind==='snake'?new PocketSnake():new MemoryPairs();this.recorded=false;this.open(kind);}
 key(key){const direction={arrowup:[0,-1],arrowdown:[0,1],arrowleft:[-1,0],arrowright:[1,0]}[key];if(this.view==='snake'&&direction)this.game?.turn(...direction);}
 update(dt){if(this.view==='call'){const el=document.getElementById('call-status');if(el)el.textContent=this.phone.call?.status||'Call ended';}const game=this.game;if(!game||!['snake','memory'].includes(this.view))return;game.update(dt);const score=document.getElementById('phone-score');if(!score)return;
  if(this.view==='snake'){const c=document.getElementById('phone-game'),ctx=c.getContext('2d');ctx.fillStyle='#c3c98b';ctx.fillRect(0,0,288,288);ctx.fillStyle='#a62646';if(game.food)ctx.fillRect(game.food.x*24+3,game.food.y*24+3,18,18);ctx.fillStyle='#383536';for(const p of game.body)ctx.fillRect(p.x*24+1,p.y*24+1,22,22);score.textContent=(game.over?'GAME OVER · ':'')+'Score '+game.score;if(game.over&&!this.recorded){this.recorded=true;this.phone.data.snakeBest=Math.max(this.phone.data.snakeBest,game.score);this.actions.save();}}
  else{document.querySelectorAll('[data-memory]').forEach(b=>{const i=Number(b.dataset.memory),up=game.open.includes(i)||game.matched.includes(i);b.textContent=up?['◆','●','▲','★','☀','♥'][game.cards[i]]:'?';b.classList.toggle('matched',game.matched.includes(i));});score.textContent=(game.won?'COMPLETE · ':'')+game.moves+' moves';if(game.won&&!this.recorded){this.recorded=true;this.phone.data.memoryBest=this.phone.data.memoryBest?Math.min(this.phone.data.memoryBest,game.moves):game.moves;this.actions.save();}}
 }
}
