import * as THREE from 'three';
import {part} from './mobility-models.js';
import {distance} from './physics.js';
function animalModel(type){const mesh=new THREE.Group(),color=type==='dog'?'#c0a179':type==='deer'?'#977554':'#59483e';part(mesh,1,.65,1.5,color,0,.7,0);part(mesh,.65,.55,.7,color,0,1.1,.85);for(const x of [-.35,.35])for(const z of [-.5,.5])part(mesh,.16,.6,.16,color,x,.3,z);for(const x of [-.2,.2])part(mesh,.12,.4,.15,color,x,1.45,.8);if(type==='boar')for(const x of [-.25,.25])part(mesh,.1,.13,.4,'#faf7ee',x,.85,1.2);if(type==='deer')for(const x of [-.23,.23])part(mesh,.07,.65,.07,'#c9bc9f',x,1.8,.7);return mesh;}
export class Wildlife{
 constructor(scene,collision,audio){this.scene=scene;this.collision=collision;this.audio=audio;this.animals=[['dog',-250,56],['dog',-12,39],['deer',-180,-157],['deer',-176,-157],['boar',-204,-198],['boar',-200,-200]].map(([type,x,z],i)=>{for(let n=0;collision.blocked(x,z,.7)&&n<20;n++)x+=1;const mesh=animalModel(type);scene.add(mesh);return {id:'animal-'+i,type,x,z,home:{x,z},mesh,health:60,dead:false,cooldown:0,friend:false};});this.birds=Array.from({length:12},(_,i)=>{const mesh=new THREE.Group();part(mesh,.2,.15,.5,'#383536');const wings=[-1,1].map(side=>part(mesh,.8,.05,.25,'#faf7ee',side*.45,0,0));scene.add(mesh);return {mesh,wings,i};});}
 targets(){return this.animals.filter(a=>!a.dead).map(a=>({x:a.x,z:a.z,animal:a}));}
 hurt(a,damage,s){a.health=Math.max(0,a.health-damage);a.scaredUntil=s.elapsed+15;a.dead=!a.health;if(a.dead){a.deadAt=s.elapsed;a.mesh.rotation.z=1.4;}else a.aggressive=a.type==='boar';}
 nearest(s){return this.animals.find(a=>a.type==='dog'&&!a.dead&&distance(a,s)<2.6);}
 pet(a,s){a.friend=true;this.audio.chirp(220,.18,.08);return 'A friend made. The dog will walk nearby.';}
 update(dt,s,onDamage){for(const a of this.animals){a.hitCooldown=Math.max(0,(a.hitCooldown||0)-dt);if(a.impulse){this.collision.move(a,a.impulse.x*dt,a.impulse.z*dt,.65);a.impulse.x*=Math.exp(-dt*4);a.impulse.z*=Math.exp(-dt*4);a.mesh.position.x=a.x;a.mesh.position.z=a.z;}a.mesh.visible=!s.interior&&distance(a,s)<150&&(!a.dead||s.elapsed-a.deadAt<60);if(a.dead)continue;const d=distance(a,s),panic=s.tornado&&Math.hypot(a.x-s.tornado.x,a.z-s.tornado.z)<60||a.scaredUntil>s.elapsed||a.type==='deer'&&d<9;let goal={x:a.home.x+Math.sin(s.elapsed*.09)*4,z:a.home.z+Math.cos(s.elapsed*.07)*4},speed=1;
 if(panic){goal={x:a.x+(a.x-s.x),z:a.z+(a.z-s.z)};speed=5;}else if(a.type==='boar'&&d<10&&!s.interior){goal=s;speed=4;a.aggressive=true;if(d<2&&s.elapsed>a.cooldown&&s.altitude<2&&this.collision.lineClear(a,s,.1,.7)){onDamage(12);a.cooldown=s.elapsed+1.8;this.audio.noiseHit(.2,.15,160);}}else if(a.friend&&d<30){goal=s;speed=d>4?3:0;}
 const len=distance(a,goal);if(len>1.8&&speed){this.collision.move(a,(goal.x-a.x)/len*speed*dt,(goal.z-a.z)/len*speed*dt,.65);a.mesh.rotation.y=Math.atan2(goal.x-a.x,goal.z-a.z);}a.mesh.position.set(a.x,.22+Math.abs(Math.sin(s.elapsed*speed*6))*.05,a.z);}
 for(const b of this.birds){const t=s.elapsed*.18+b.i;b.mesh.visible=!s.interior;b.mesh.position.set(-100+Math.sin(t)*95,15+b.i%4*3,40+Math.cos(t*.8)*120);b.mesh.rotation.y=-t;b.wings.forEach((w,i)=>w.rotation.z=Math.sin(s.elapsed*8+b.i)*.65*(i?1:-1));}}
}
